<?php
/**
 * @package    Joomla.Component.Builder
 *
 * @created    4th September, 2022
 * @author     Llewellyn van der Merwe <https://dev.vdm.io>
 * @git        Joomla Component Builder <https://git.vdm.dev/joomla/Component-Builder>
 * @copyright  Copyright (C) 2015 Vast Development Method. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */

namespace JoomService\Joomla\Servicedirectory;


use JoomService\Joomla\Interfaces\TableInterface;
use JoomService\Joomla\Abstraction\BaseTable;


/**
 * Servicedirectory Table Definition Class.
 * 
 * This class provides a centralized definition of all database-backed
 * areas, views, and their fields for Servicedirectory.
 * 
 * It maps component entities to their schema definitions, field metadata,
 * storage behaviour, and relationships, enabling consistent code generation
 * and runtime operations across models, forms, and SQL migrations.
 * 
 * @since 3.2.0
 */
class Table extends BaseTable implements TableInterface
{
	/**
	 * Table Schema and Field Metadata Map.
	 *
	 * A fully structured, associative array containing definitions for
	 * every database table (area/view) used by the component. Each table
	 * contains its field definitions with the following details:
	 *
	 * - **name**: The column/field name in the database.
	 * - **label**: The Joomla language constant for field display text.
	 * - **type**: The form field type (text, textarea, editor, radio, list, etc.).
	 * - **title**: Whether this field is the primary title field for the view.
	 * - **list**: The list view this field belongs to.
	 * - **store**: Any special storage encoding (e.g. `base64`, `json`, `basic_encryption`).
	 * - **tab_name**: The logical tab grouping for form display.
	 * - **db**: An array describing the database column definition:
	 *   - `type`: The SQL column type (e.g. VARCHAR(255), INT(11)).
	 *   - `default`: Default value or `EMPTY`.
	 *   - `GUID`: A unique identifier.
	 *   - `null_switch`: Whether NULL is allowed (`NULL` or `NOT NULL`).
	 *   - `unique_key`: Boolean indicating if a unique key is enforced.
	 *   - `key`: Boolean indicating if it is indexed.
	 * - **link**: If applicable, describes a foreign key relationship
	 *   (target table, component, entity, value field, and key field).
	 * - **fields**: (Optional) Subfield definitions for subforms.
	 *
	 * This array is the canonical reference used by developers to dynamically
	 * build database migrations, generate forms, create models, and ensure
	 * consistent schema management across installations and updates.
	 *
	 * @var   array
	 * @since 3.2.0
	 */
	protected array $tables = [
		'ticket' => [
			'subject' => [
				'name' => 'subject',
				'guid' => 'f0ad9a75-6e97-4b2e-a6b0-51c7a8815312',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_SUBJECT_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'tickets',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f0ad9a75-6e97-4b2e-a6b0-51c7a8815312',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'tickets',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'priority' => [
				'name' => 'priority',
				'guid' => 'b54dba1f-bfdc-49a2-95c4-3bbcea0861f0',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_PRIORITY_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'tickets',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '1',
					'GUID' => 'b54dba1f-bfdc-49a2-95c4-3bbcea0861f0',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'published' => [
				'name' => 'published',
				'guid' => '3ccf9728-ceb0-4ee2-95c6-5ab0ceb5f06e',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_PUBLISHED_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'tickets',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '3ccf9728-ceb0-4ee2-95c6-5ab0ceb5f06e',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'tickets',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'company' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'contactname' => [
				'name' => 'contactname',
				'guid' => '5711daf2-43c4-4b35-9d0c-b96962062734',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_CONTACTNAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5711daf2-43c4-4b35-9d0c-b96962062734',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'category' => [
				'name' => 'category',
				'guid' => 'b8dbe7d5-50d5-44e1-ab69-8b86b3a4a160',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_CATEGORY_LABEL',
				'type' => 'categories',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => 'b8dbe7d5-50d5-44e1-ab69-8b86b3a4a160',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_category',
					'component' => 'com_servicedirectory',
					'entity' => 'category',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'created_by' => [
				'name' => 'created_by',
				'guid' => 'cdb60c2c-8961-446c-ab8c-7ff3dc960091',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_CREATED_BY_LABEL',
				'type' => 'user',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'cdb60c2c-8961-446c-ab8c-7ff3dc960091',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'chamber_of_commerce' => [
				'name' => 'chamber_of_commerce',
				'guid' => '1a67060a-9e45-4b3b-8be6-8025bf3a3026',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_CHAMBER_OF_COMMERCE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '1a67060a-9e45-4b3b-8be6-8025bf3a3026',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'email' => [
				'name' => 'email',
				'guid' => 'ba32af1e-0b57-4dcc-b9bb-7cec104c0ee7',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_EMAIL_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'ba32af1e-0b57-4dcc-b9bb-7cec104c0ee7',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'alias' => [
				'name' => 'alias',
				'guid' => '335866ce-b81b-4329-901d-c20254135c9c',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_ALIAS_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(64)',
					'default' => '',
					'GUID' => '335866ce-b81b-4329-901d-c20254135c9c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'company_type' => [
				'name' => 'company_type',
				'guid' => '80fa4894-de6b-495f-9343-42b481edc385',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_COMPANY_TYPE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '80fa4894-de6b-495f-9343-42b481edc385',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_DESCRIPTION_LABEL',
				'type' => 'editor',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(2048)',
					'default' => '',
					'GUID' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'website' => [
				'name' => 'website',
				'guid' => 'b84bc31f-90ba-44bc-8808-c8fb3248ccd5',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_WEBSITE_LABEL',
				'type' => 'url',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'b84bc31f-90ba-44bc-8808-c8fb3248ccd5',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'phone' => [
				'name' => 'phone',
				'guid' => '76886659-3578-4091-8c00-330c85f618dc',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_PHONE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Contact info',
				'db' => [
					'type' => 'VARCHAR(50)',
					'default' => '',
					'GUID' => '76886659-3578-4091-8c00-330c85f618dc',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'companysize' => [
				'name' => 'companysize',
				'guid' => 'e4fff45e-0335-44f6-9dc7-54f2dc81d659',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_COMPANYSIZE_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'companies',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'e4fff45e-0335-44f6-9dc7-54f2dc81d659',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
			'metakey' => [
				'name' => 'metakey',
				'label' => 'Meta Keywords',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadesc' => [
				'name' => 'metadesc',
				'label' => 'Meta Description',
				'type' => 'textarea',
				'title' => false,
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
			'metadata' => [
				'name' => 'metadata',
				'label' => 'Meta Data',
				'type' => NULL,
				'title' => false,
				'store' => 'json',
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'TEXT',
				],
			],
		],
		'portfolio' => [
			'project_title' => [
				'name' => 'project_title',
				'guid' => '1a2db720-19ca-40ff-9570-452bbcebd95b',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_PROJECT_TITLE_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '1a2db720-19ca-40ff-9570-452bbcebd95b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'client_name' => [
				'name' => 'client_name',
				'guid' => '28caada9-4354-4e87-bd62-4624a0761a9a',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_CLIENT_NAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '28caada9-4354-4e87-bd62-4624a0761a9a',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'target_industry' => [
				'name' => 'target_industry',
				'guid' => 'bf24f5e2-a0bf-4db0-b993-8c836f9e5b44',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_TARGET_INDUSTRY_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'bf24f5e2-a0bf-4db0-b993-8c836f9e5b44',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_DESCRIPTION_LABEL',
				'type' => 'editor',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(2048)',
					'default' => '',
					'GUID' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'project_url' => [
				'name' => 'project_url',
				'guid' => '820760db-d634-4f5e-8c5f-63a5709e0d93',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_PROJECT_URL_LABEL',
				'type' => 'url',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '820760db-d634-4f5e-8c5f-63a5709e0d93',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'services_provided' => [
				'name' => 'services_provided',
				'guid' => '8afc97dd-c485-48a5-9723-07df1a15af89',
				'label' => 'COM_SERVICEDIRECTORY_PORTFOLIO_SERVICES_PROVIDED_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'portfolios',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '8afc97dd-c485-48a5-9723-07df1a15af89',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'category' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_DESCRIPTION_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'parent_guid' => [
				'name' => 'parent_guid',
				'guid' => '1737aa23-d70c-4ca1-b242-bfa508cb328c',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_PARENT_GUID_LABEL',
				'type' => 'categories',
				'title' => false,
				'list' => 'categories',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '1737aa23-d70c-4ca1-b242-bfa508cb328c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_category',
					'component' => 'com_servicedirectory',
					'entity' => 'category',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'published' => [
				'name' => 'published',
				'guid' => '6debe7be-69ad-4238-9114-288759578256',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_PUBLISHED_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '6debe7be-69ad-4238-9114-288759578256',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'lft' => [
				'name' => 'lft',
				'guid' => '4f6b179b-3a78-4276-86a4-713834e1bdf5',
				'label' => '',
				'type' => 'hidden',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '4f6b179b-3a78-4276-86a4-713834e1bdf5',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'rgt' => [
				'name' => 'rgt',
				'guid' => '413bc704-27e8-4826-864f-855324c98e22',
				'label' => '',
				'type' => 'hidden',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '413bc704-27e8-4826-864f-855324c98e22',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'level' => [
				'name' => 'level',
				'guid' => '1540695d-e93a-4182-bdbe-42660a305d3f',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_LEVEL_LABEL',
				'type' => 'integer',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '1540695d-e93a-4182-bdbe-42660a305d3f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'alias' => [
				'name' => 'alias',
				'guid' => '335866ce-b81b-4329-901d-c20254135c9c',
				'label' => 'COM_SERVICEDIRECTORY_CATEGORY_ALIAS_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'categories',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(64)',
					'default' => '',
					'GUID' => '335866ce-b81b-4329-901d-c20254135c9c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'tag' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_TAG_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
				'label' => 'COM_SERVICEDIRECTORY_TAG_DESCRIPTION_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'parent_guid' => [
				'name' => 'parent_guid',
				'guid' => '0e2bbd0e-44a5-47d3-af8b-564d4ac29f9b',
				'label' => 'COM_SERVICEDIRECTORY_TAG_PARENT_GUID_LABEL',
				'type' => 'tags',
				'title' => false,
				'list' => 'tags',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '0e2bbd0e-44a5-47d3-af8b-564d4ac29f9b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_tag',
					'component' => 'com_servicedirectory',
					'entity' => 'tag',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'published' => [
				'name' => 'published',
				'guid' => '6debe7be-69ad-4238-9114-288759578256',
				'label' => 'COM_SERVICEDIRECTORY_TAG_PUBLISHED_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '6debe7be-69ad-4238-9114-288759578256',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_TAG_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'lft' => [
				'name' => 'lft',
				'guid' => '4f6b179b-3a78-4276-86a4-713834e1bdf5',
				'label' => '',
				'type' => 'hidden',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '4f6b179b-3a78-4276-86a4-713834e1bdf5',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'rgt' => [
				'name' => 'rgt',
				'guid' => '413bc704-27e8-4826-864f-855324c98e22',
				'label' => '',
				'type' => 'hidden',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '413bc704-27e8-4826-864f-855324c98e22',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'level' => [
				'name' => 'level',
				'guid' => '1540695d-e93a-4182-bdbe-42660a305d3f',
				'label' => 'COM_SERVICEDIRECTORY_TAG_LEVEL_LABEL',
				'type' => 'integer',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '1540695d-e93a-4182-bdbe-42660a305d3f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'alias' => [
				'name' => 'alias',
				'guid' => '335866ce-b81b-4329-901d-c20254135c9c',
				'label' => 'COM_SERVICEDIRECTORY_TAG_ALIAS_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(64)',
					'default' => '',
					'GUID' => '335866ce-b81b-4329-901d-c20254135c9c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'social_handle' => [
			'platform' => [
				'name' => 'platform',
				'guid' => '332d557b-27ed-4346-98ab-2e06b4209d2d',
				'label' => 'COM_SERVICEDIRECTORY_SOCIAL_HANDLE_PLATFORM_LABEL',
				'type' => 'ModalSelect',
				'title' => true,
				'list' => 'social_handles',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '332d557b-27ed-4346-98ab-2e06b4209d2d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_platform',
					'component' => 'com_servicedirectory',
					'entity' => 'platform',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'handle' => [
				'name' => 'handle',
				'guid' => 'd8d19384-f81c-4655-bd21-30149c2d4ead',
				'label' => 'COM_SERVICEDIRECTORY_SOCIAL_HANDLE_HANDLE_LABEL',
				'type' => 'url',
				'title' => false,
				'list' => 'social_handles',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'd8d19384-f81c-4655-bd21-30149c2d4ead',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_SOCIAL_HANDLE_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'social_handles',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_SOCIAL_HANDLE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'social_handles',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'area_of_expertise' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_AREA_OF_EXPERTISE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
				'label' => 'COM_SERVICEDIRECTORY_AREA_OF_EXPERTISE_DESCRIPTION_LABEL',
				'type' => 'editor',
				'title' => false,
				'list' => 'areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(2048)',
					'default' => '',
					'GUID' => '7ba7c96e-6838-4a3d-8dc6-bb1328b4e46f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_AREA_OF_EXPERTISE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'alias' => [
				'name' => 'alias',
				'guid' => '335866ce-b81b-4329-901d-c20254135c9c',
				'label' => 'COM_SERVICEDIRECTORY_AREA_OF_EXPERTISE_ALIAS_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(64)',
					'default' => '',
					'GUID' => '335866ce-b81b-4329-901d-c20254135c9c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'file' => [
			'name' => [
				'name' => 'name',
				'guid' => '725e856a-b8cc-4590-90e3-3eed6fd0873c',
				'label' => 'COM_SERVICEDIRECTORY_FILE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '725e856a-b8cc-4590-90e3-3eed6fd0873c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'file_type' => [
				'name' => 'file_type',
				'guid' => 'c2f884f9-31a0-4bb9-8310-64b5d9132d32',
				'label' => 'COM_SERVICEDIRECTORY_FILE_FILE_TYPE_LABEL',
				'type' => 'filetypes',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'c2f884f9-31a0-4bb9-8310-64b5d9132d32',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_file_type',
					'component' => 'com_servicedirectory',
					'entity' => 'file_type',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'size' => [
				'name' => 'size',
				'guid' => '77a1711b-ad1f-4379-921b-5e4ef5c31a42',
				'label' => 'COM_SERVICEDIRECTORY_FILE_SIZE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '77a1711b-ad1f-4379-921b-5e4ef5c31a42',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'entity_type' => [
				'name' => 'entity_type',
				'guid' => '2e24a9fe-5793-46be-b071-631c0b18d8f4',
				'label' => 'COM_SERVICEDIRECTORY_FILE_ENTITY_TYPE_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '2e24a9fe-5793-46be-b071-631c0b18d8f4',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_FILE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'entity' => [
				'name' => 'entity',
				'guid' => '3f1fedeb-b943-42a7-88e7-c4f1eb1fd8a4',
				'label' => 'COM_SERVICEDIRECTORY_FILE_ENTITY_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '3f1fedeb-b943-42a7-88e7-c4f1eb1fd8a4',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'file_path' => [
				'name' => 'file_path',
				'guid' => 'ed28e30c-30c3-4830-afdc-5a61bf25cd49',
				'label' => 'COM_SERVICEDIRECTORY_FILE_FILE_PATH_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(1024)',
					'default' => '',
					'GUID' => 'ed28e30c-30c3-4830-afdc-5a61bf25cd49',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'extension' => [
				'name' => 'extension',
				'guid' => '080b92dc-a4b4-46b2-83d4-3430284f5e06',
				'label' => 'COM_SERVICEDIRECTORY_FILE_EXTENSION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '080b92dc-a4b4-46b2-83d4-3430284f5e06',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'mime' => [
				'name' => 'mime',
				'guid' => '68c1e141-fb2e-49a6-bf56-1da6d8a058e8',
				'label' => 'COM_SERVICEDIRECTORY_FILE_MIME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'files',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '68c1e141-fb2e-49a6-bf56-1da6d8a058e8',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'address' => [
			'line_one' => [
				'name' => 'line_one',
				'guid' => 'e5a082f3-54ab-4ab6-8691-afd195346d77',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_LINE_ONE_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'e5a082f3-54ab-4ab6-8691-afd195346d77',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'type' => [
				'name' => 'type',
				'guid' => '19369aa2-33cf-4be4-8faf-7bd74e542971',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_TYPE_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '19369aa2-33cf-4be4-8faf-7bd74e542971',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_address_type',
					'component' => 'com_servicedirectory',
					'entity' => 'address_type',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'country' => [
				'name' => 'country',
				'guid' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_COUNTRY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_country',
					'component' => 'com_servicedirectory',
					'entity' => 'country',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'state' => [
				'name' => 'state',
				'guid' => '1e666136-800a-486d-a8e8-13a054b7acde',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_STATE_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '1e666136-800a-486d-a8e8-13a054b7acde',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_state',
					'component' => 'com_servicedirectory',
					'entity' => 'state',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'city' => [
				'name' => 'city',
				'guid' => 'c069c4a5-f693-4e18-aee4-11292bf7fec8',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_CITY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => 'c069c4a5-f693-4e18-aee4-11292bf7fec8',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_city',
					'component' => 'com_servicedirectory',
					'entity' => 'city',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'postal' => [
				'name' => 'postal',
				'guid' => 'e769beb6-f761-4885-8d35-eb2f0be55ee6',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_POSTAL_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'e769beb6-f761-4885-8d35-eb2f0be55ee6',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'line_two' => [
				'name' => 'line_two',
				'guid' => 'cc0e70fa-bdda-474c-95c1-0ad5f1e9ec3c',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_LINE_TWO_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'addresses',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'cc0e70fa-bdda-474c-95c1-0ad5f1e9ec3c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'region' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_REGION_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'regions',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_REGION_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'regions',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'wikidataid' => [
				'name' => 'wikidataid',
				'guid' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
				'label' => 'COM_SERVICEDIRECTORY_REGION_WIKIDATAID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'regions',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'subregion' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_SUBREGION_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'subregions',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'region' => [
				'name' => 'region',
				'guid' => '7f3ccb20-7c57-433a-987b-b53d801004f3',
				'label' => 'COM_SERVICEDIRECTORY_SUBREGION_REGION_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'subregions',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '7f3ccb20-7c57-433a-987b-b53d801004f3',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_region',
					'component' => 'com_servicedirectory',
					'entity' => 'region',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_SUBREGION_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'subregions',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'wikidataid' => [
				'name' => 'wikidataid',
				'guid' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
				'label' => 'COM_SERVICEDIRECTORY_SUBREGION_WIKIDATAID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'subregions',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'country' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'subregion' => [
				'name' => 'subregion',
				'guid' => '19b4a840-cf4e-4012-8fae-b1439af74f5a',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_SUBREGION_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '19b4a840-cf4e-4012-8fae-b1439af74f5a',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_subregion',
					'component' => 'com_servicedirectory',
					'entity' => 'subregion',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'capital' => [
				'name' => 'capital',
				'guid' => 'baeaf484-f61b-4688-8b8a-e3ace669b7a7',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_CAPITAL_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => 'baeaf484-f61b-4688-8b8a-e3ace669b7a7',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_city',
					'component' => 'com_servicedirectory',
					'entity' => 'city',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'currency_name' => [
				'name' => 'currency_name',
				'guid' => '4b964b88-36b4-4f26-a828-0e798ce9af38',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_CURRENCY_NAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '4b964b88-36b4-4f26-a828-0e798ce9af38',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'latitude' => [
				'name' => 'latitude',
				'guid' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_LATITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(10,8)',
					'default' => '0',
					'GUID' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'emojiu' => [
				'name' => 'emojiu',
				'guid' => 'b71ee1ab-78ea-4cc7-aa2e-490a4d01a03f',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_EMOJIU_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(191)',
					'default' => '',
					'GUID' => 'b71ee1ab-78ea-4cc7-aa2e-490a4d01a03f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'emoji' => [
				'name' => 'emoji',
				'guid' => '962ec39f-78d4-42ee-9626-7b778d2eea25',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_EMOJI_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(191)',
					'default' => '',
					'GUID' => '962ec39f-78d4-42ee-9626-7b778d2eea25',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'tld' => [
				'name' => 'tld',
				'guid' => 'c4c23fad-fd03-41cc-b5db-25f60b8ee11f',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_TLD_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'c4c23fad-fd03-41cc-b5db-25f60b8ee11f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'iso2' => [
				'name' => 'iso2',
				'guid' => '2039d1c3-162c-401c-96fe-f127683ee3fe',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_ISO2_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(7)',
					'default' => '',
					'GUID' => '2039d1c3-162c-401c-96fe-f127683ee3fe',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'codethree' => [
				'name' => 'codethree',
				'guid' => '59f0d051-768e-41de-87a0-f47551f7d0d1',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_CODETHREE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(7)',
					'default' => '',
					'GUID' => '59f0d051-768e-41de-87a0-f47551f7d0d1',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'nationality' => [
				'name' => 'nationality',
				'guid' => '8ba72283-32fa-4a34-8c0d-d52adfed1aa5',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_NATIONALITY_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '8ba72283-32fa-4a34-8c0d-d52adfed1aa5',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'native' => [
				'name' => 'native',
				'guid' => '2aad92a4-895d-46cb-b0df-751da1bdd703',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_NATIVE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '2aad92a4-895d-46cb-b0df-751da1bdd703',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'longitude' => [
				'name' => 'longitude',
				'guid' => '09c22738-6c6f-48ca-a24d-d439757e8619',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_LONGITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(11,8)',
					'default' => '0',
					'GUID' => '09c22738-6c6f-48ca-a24d-d439757e8619',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'symbol' => [
				'name' => 'symbol',
				'guid' => 'c9a4c765-a0f9-42da-8fa9-df41ab70c448',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_SYMBOL_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(11)',
					'default' => '',
					'GUID' => 'c9a4c765-a0f9-42da-8fa9-df41ab70c448',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'numeric_code' => [
				'name' => 'numeric_code',
				'guid' => '40da896f-5054-4bb2-aa58-1cdfb391f544',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_NUMERIC_CODE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(10)',
					'default' => '0',
					'GUID' => '40da896f-5054-4bb2-aa58-1cdfb391f544',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'wikidataid' => [
				'name' => 'wikidataid',
				'guid' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_WIKIDATAID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'phonecode' => [
				'name' => 'phonecode',
				'guid' => '149140a8-d0a6-4b62-a880-bb796e2145d8',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_PHONECODE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '149140a8-d0a6-4b62-a880-bb796e2145d8',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'iso3' => [
				'name' => 'iso3',
				'guid' => '95f46f99-0909-4a47-879b-ede06ef35fb8',
				'label' => 'COM_SERVICEDIRECTORY_COUNTRY_ISO3_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'countries',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(7)',
					'default' => '',
					'GUID' => '95f46f99-0909-4a47-879b-ede06ef35fb8',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'state' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_STATE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'country' => [
				'name' => 'country',
				'guid' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
				'label' => 'COM_SERVICEDIRECTORY_STATE_COUNTRY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_country',
					'component' => 'com_servicedirectory',
					'entity' => 'country',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'type' => [
				'name' => 'type',
				'guid' => '4321fa80-702d-4ff5-ab3c-05507d3007a9',
				'label' => 'COM_SERVICEDIRECTORY_STATE_TYPE_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '4321fa80-702d-4ff5-ab3c-05507d3007a9',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_STATE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'wikidataid' => [
				'name' => 'wikidataid',
				'guid' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
				'label' => 'COM_SERVICEDIRECTORY_STATE_WIKIDATAID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'fips_code' => [
				'name' => 'fips_code',
				'guid' => 'fa0ead84-06c8-4f18-89ae-4cdf646fd961',
				'label' => 'COM_SERVICEDIRECTORY_STATE_FIPS_CODE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'fa0ead84-06c8-4f18-89ae-4cdf646fd961',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'iso2' => [
				'name' => 'iso2',
				'guid' => '2039d1c3-162c-401c-96fe-f127683ee3fe',
				'label' => 'COM_SERVICEDIRECTORY_STATE_ISO2_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'CHAR(7)',
					'default' => '',
					'GUID' => '2039d1c3-162c-401c-96fe-f127683ee3fe',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'longitude' => [
				'name' => 'longitude',
				'guid' => '09c22738-6c6f-48ca-a24d-d439757e8619',
				'label' => 'COM_SERVICEDIRECTORY_STATE_LONGITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(11,8)',
					'default' => '0',
					'GUID' => '09c22738-6c6f-48ca-a24d-d439757e8619',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'latitude' => [
				'name' => 'latitude',
				'guid' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
				'label' => 'COM_SERVICEDIRECTORY_STATE_LATITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'states',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(10,8)',
					'default' => '0',
					'GUID' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'city' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_CITY_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'state' => [
				'name' => 'state',
				'guid' => '1e666136-800a-486d-a8e8-13a054b7acde',
				'label' => 'COM_SERVICEDIRECTORY_CITY_STATE_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '1e666136-800a-486d-a8e8-13a054b7acde',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_state',
					'component' => 'com_servicedirectory',
					'entity' => 'state',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'latitude' => [
				'name' => 'latitude',
				'guid' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
				'label' => 'COM_SERVICEDIRECTORY_CITY_LATITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(10,8)',
					'default' => '0',
					'GUID' => 'f7d3d78e-2d35-4884-a997-d073f853d095',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'longitude' => [
				'name' => 'longitude',
				'guid' => '09c22738-6c6f-48ca-a24d-d439757e8619',
				'label' => 'COM_SERVICEDIRECTORY_CITY_LONGITUDE_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'DECIMAL(11,8)',
					'default' => '0',
					'GUID' => '09c22738-6c6f-48ca-a24d-d439757e8619',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_CITY_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'wikidataid' => [
				'name' => 'wikidataid',
				'guid' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
				'label' => 'COM_SERVICEDIRECTORY_CITY_WIKIDATAID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'cities',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'af59b3ac-6a00-42c0-bbe2-edf90dec6081',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'timezone' => [
			'timezone_name' => [
				'name' => 'timezone_name',
				'guid' => 'f921d762-f5f1-4811-b1f5-71840c003a4e',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_TIMEZONE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'f921d762-f5f1-4811-b1f5-71840c003a4e',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'timezone_identifier' => [
				'name' => 'timezone_identifier',
				'guid' => 'c20d4692-6e97-4441-83bd-561b73730407',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_TIMEZONE_IDENTIFIER_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'c20d4692-6e97-4441-83bd-561b73730407',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'gmt_offset_name' => [
				'name' => 'gmt_offset_name',
				'guid' => '480c9734-2820-4a61-afea-75b1db3fadc9',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_GMT_OFFSET_NAME_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '480c9734-2820-4a61-afea-75b1db3fadc9',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'country' => [
				'name' => 'country',
				'guid' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_COUNTRY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '8d1b9d7e-77c1-43d9-bc97-0dd021bfe779',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_country',
					'component' => 'com_servicedirectory',
					'entity' => 'country',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'gmt_offset_sec' => [
				'name' => 'gmt_offset_sec',
				'guid' => '17788601-b3f8-439e-8ad7-11c7f8109e22',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_GMT_OFFSET_SEC_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '17788601-b3f8-439e-8ad7-11c7f8109e22',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'abbreviation' => [
				'name' => 'abbreviation',
				'guid' => 'c35e18fa-cade-48b8-b067-6289cc7a0f60',
				'label' => 'COM_SERVICEDIRECTORY_TIMEZONE_ABBREVIATION_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'timezones',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => 'c35e18fa-cade-48b8-b067-6289cc7a0f60',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'platform' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_PLATFORM_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'platforms',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'website' => [
				'name' => 'website',
				'guid' => 'b84bc31f-90ba-44bc-8808-c8fb3248ccd5',
				'label' => 'COM_SERVICEDIRECTORY_PLATFORM_WEBSITE_LABEL',
				'type' => 'url',
				'title' => false,
				'list' => 'platforms',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => 'b84bc31f-90ba-44bc-8808-c8fb3248ccd5',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'icon' => [
				'name' => 'icon',
				'guid' => 'dde7015f-ffe1-46a1-b24f-8e9e93aefb38',
				'label' => 'COM_SERVICEDIRECTORY_PLATFORM_ICON_LABEL',
				'type' => 'icons',
				'title' => false,
				'list' => 'platforms',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => 'dde7015f-ffe1-46a1-b24f-8e9e93aefb38',
					'null_switch' => 'NOT NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 2,
					'table' => '',
					'component' => '',
					'entity' => '',
					'value' => '',
					'key' => '',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_PLATFORM_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'platforms',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'language' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_LANGUAGE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'languages',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'langtag' => [
				'name' => 'langtag',
				'guid' => '8fdf3640-8668-4818-be46-36c74f9e103e',
				'label' => 'COM_SERVICEDIRECTORY_LANGUAGE_LANGTAG_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'languages',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => '8fdf3640-8668-4818-be46-36c74f9e103e',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'address_type' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_TYPE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'address_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'description' => [
				'name' => 'description',
				'guid' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_TYPE_DESCRIPTION_LABEL',
				'type' => 'textarea',
				'title' => false,
				'list' => 'address_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '749a9917-90c3-49c4-9e72-aa33b0683a87',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_ADDRESS_TYPE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'address_types',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'file_type' => [
			'name' => [
				'name' => 'name',
				'guid' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_NAME_LABEL',
				'type' => 'text',
				'title' => true,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '5d3d34dd-4876-4c6a-86ab-b4e162f22c08',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'type' => [
				'name' => 'type',
				'guid' => '9f6f776f-9741-4aec-a3ff-fb9880fdcb5c',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_TYPE_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TINYINT(1)',
					'default' => '0',
					'GUID' => '9f6f776f-9741-4aec-a3ff-fb9880fdcb5c',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'path' => [
				'name' => 'path',
				'guid' => '523f91f8-ca60-44f7-9de0-645549967095',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_PATH_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '523f91f8-ca60-44f7-9de0-645549967095',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'download_access' => [
				'name' => 'download_access',
				'guid' => '794ac8d4-c78b-4f98-9953-07e4ce5ad491',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_DOWNLOAD_ACCESS_LABEL',
				'type' => 'accesslevel',
				'title' => false,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => '794ac8d4-c78b-4f98-9953-07e4ce5ad491',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'quantity' => [
				'name' => 'quantity',
				'guid' => 'e8c5a0cc-31fd-425e-9ebd-35716e3e140d',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_QUANTITY_LABEL',
				'type' => 'number',
				'title' => false,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'INT(11)',
					'default' => '0',
					'GUID' => 'e8c5a0cc-31fd-425e-9ebd-35716e3e140d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'file_types',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'target' => [
				'name' => 'target',
				'guid' => 'e24026ef-294a-48e5-9be0-3f95dcb2b66b',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_TARGET_LABEL',
				'type' => 'list',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(64)',
					'default' => '',
					'GUID' => 'e24026ef-294a-48e5-9be0-3f95dcb2b66b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'crop' => [
				'name' => 'crop',
				'guid' => '6f327030-dcdf-4d80-b3d9-293d4bbe39f7',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_CROP_LABEL',
				'type' => 'subform',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '6f327030-dcdf-4d80-b3d9-293d4bbe39f7',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
				'fields' => [
					'name' => [
						'name' => 'name',
						'type' => 'text',
						'link' => NULL,
					],
					'height' => [
						'name' => 'height',
						'type' => 'text',
						'link' => NULL,
					],
					'width' => [
						'name' => 'width',
						'type' => 'text',
						'link' => NULL,
					],
				],
			],
			'file_formats' => [
				'name' => 'file_formats',
				'guid' => 'ca8f38cb-f930-4976-a76b-c1d6cd18652d',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_FILE_FORMATS_LABEL',
				'type' => 'allowedfileformats',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => 'ca8f38cb-f930-4976-a76b-c1d6cd18652d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 2,
					'table' => '',
					'component' => '',
					'entity' => '',
					'value' => '',
					'key' => '',
				],
			],
			'document_formats' => [
				'name' => 'document_formats',
				'guid' => '24f17aaf-cc19-4bad-bc8b-4d37c79a898d',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_DOCUMENT_FORMATS_LABEL',
				'type' => 'alloweddocumentformats',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '24f17aaf-cc19-4bad-bc8b-4d37c79a898d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 2,
					'table' => '',
					'component' => '',
					'entity' => '',
					'value' => '',
					'key' => '',
				],
			],
			'media_formats' => [
				'name' => 'media_formats',
				'guid' => 'fd936809-37c1-4016-a4ee-a4d016343725',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_MEDIA_FORMATS_LABEL',
				'type' => 'allowedmediaformats',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => 'fd936809-37c1-4016-a4ee-a4d016343725',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 2,
					'table' => '',
					'component' => '',
					'entity' => '',
					'value' => '',
					'key' => '',
				],
			],
			'image_formats' => [
				'name' => 'image_formats',
				'guid' => '6b3c73d5-7640-43c0-a2e7-125a187f4513',
				'label' => 'COM_SERVICEDIRECTORY_FILE_TYPE_IMAGE_FORMATS_LABEL',
				'type' => 'allowedimageformats',
				'title' => false,
				'list' => 'file_types',
				'store' => 'json',
				'tab_name' => 'Details',
				'db' => [
					'type' => 'TEXT',
					'default' => 'EMPTY',
					'GUID' => '6b3c73d5-7640-43c0-a2e7-125a187f4513',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => [
					'type' => 2,
					'table' => '',
					'component' => '',
					'entity' => '',
					'value' => '',
					'key' => '',
				],
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'company_language' => [
			'language' => [
				'name' => 'language',
				'guid' => '783a690a-38a4-490b-a913-968de6369b39',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_LANGUAGE_LANGUAGE_LABEL',
				'type' => 'ModalSelect',
				'title' => true,
				'list' => 'company_languages',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(255)',
					'default' => '',
					'GUID' => '783a690a-38a4-490b-a913-968de6369b39',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_language',
					'component' => 'com_servicedirectory',
					'entity' => 'language',
					'value' => 'name',
					'key' => 'langtag',
				],
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_LANGUAGE_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'company_languages',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_LANGUAGE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'company_languages',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'company_tag' => [
			'tag' => [
				'name' => 'tag',
				'guid' => '66f11387-8824-45b9-991d-af0c85c1f5db',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_TAG_TAG_LABEL',
				'type' => 'ModalSelect',
				'title' => true,
				'list' => 'company_tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '66f11387-8824-45b9-991d-af0c85c1f5db',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_tag',
					'component' => 'com_servicedirectory',
					'entity' => 'tag',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_TAG_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'company_tags',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_TAG_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'company_tags',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'company_area_of_expertise' => [
			'area_of_expertise' => [
				'name' => 'area_of_expertise',
				'guid' => 'bcc78ac1-30e7-46d9-8ef7-69f21528f95f',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_AREA_OF_EXPERTISE_AREA_OF_EXPERTISE_LABEL',
				'type' => 'ModalSelect',
				'title' => true,
				'list' => 'company_areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => 'bcc78ac1-30e7-46d9-8ef7-69f21528f95f',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_area_of_expertise',
					'component' => 'com_servicedirectory',
					'entity' => 'area_of_expertise',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'company' => [
				'name' => 'company',
				'guid' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_AREA_OF_EXPERTISE_COMPANY_LABEL',
				'type' => 'ModalSelect',
				'title' => false,
				'list' => 'company_areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '16a136b8-fd99-41ad-b606-628bb6a91b75',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_company',
					'component' => 'com_servicedirectory',
					'entity' => 'company',
					'value' => 'name',
					'key' => 'guid',
				],
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_COMPANY_AREA_OF_EXPERTISE_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'company_areas_of_expertise',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
		'ticket_comment' => [
			'ticket' => [
				'name' => 'ticket',
				'guid' => 'd835209a-6955-4047-bb91-3dfeed7c2e30',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_COMMENT_TICKET_LABEL',
				'type' => 'ModalSelect',
				'title' => true,
				'list' => 'ticket_comments',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => 'd835209a-6955-4047-bb91-3dfeed7c2e30',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => [
					'type' => 1,
					'table' => '#__servicedirectory_ticket',
					'component' => 'com_servicedirectory',
					'entity' => 'ticket',
					'value' => 'subject',
					'key' => 'guid',
				],
			],
			'comment' => [
				'name' => 'comment',
				'guid' => '90197849-128e-40b2-be4a-792617ab5b2d',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_COMMENT_COMMENT_LABEL',
				'type' => 'editor',
				'title' => false,
				'list' => 'ticket_comments',
				'store' => NULL,
				'tab_name' => 'Details',
				'db' => [
					'type' => 'VARCHAR(2048)',
					'default' => '',
					'GUID' => '90197849-128e-40b2-be4a-792617ab5b2d',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => false,
				],
				'link' => NULL,
			],
			'guid' => [
				'name' => 'guid',
				'guid' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
				'label' => 'COM_SERVICEDIRECTORY_TICKET_COMMENT_GUID_LABEL',
				'type' => 'text',
				'title' => false,
				'list' => 'ticket_comments',
				'store' => NULL,
				'tab_name' => 'publishing',
				'db' => [
					'type' => 'VARCHAR(36)',
					'default' => '',
					'GUID' => '5aa57bbe-7b19-4db9-915c-561863458d2b',
					'null_switch' => 'NULL',
					'unique_key' => false,
					'key' => true,
				],
				'link' => NULL,
			],
			'access' => [
				'name' => 'access',
				'label' => 'Access',
				'type' => 'accesslevel',
				'title' => false,
				'store' => NULL,
				'tab_name' => NULL,
				'db' => [
					'type' => 'INT(10) unsigned',
					'default' => '0',
					'key' => true,
					'null_switch' => 'NULL',
				],
			],
		],
	];
}

